PT-2261: Update payment module
VirtoCommerce/vc-module-payment pull request #27
Opened 2021-08-20 12:41 UTC by aizhuli

## Description
Refactor payment module to implement generic crud services
## References
### QA-test:
### Jira-link: https://virtocommerce.atlassian.net/browse/PT-2261
### Artifact URL:

2021-08-23 17:03 UTC, akak1977 requested changes

2021-08-23 17:03 UTC, akak1977 commented on src/VirtoCommerce.Payment.Data/Services/PaymentMethodsService.cs
> -            await _settingManager.DeepRemoveSettingsAsync(paymentMethods);
No equal code.

2021-08-23 17:03 UTC, akak1977 commented on src/VirtoCommerce.Payment.Core/Services/IPaymentMethodsSearchService.cs
>      }
Removing a method from the interface introduces a compatibility break.

2021-08-23 17:03 UTC, akak1977 commented on src/VirtoCommerce.Payment.Core/Services/IPaymentMethodsService.cs
>      }
Removing a method from the interface introduces a compatibility break.

2021-09-01 04:10 UTC, mvktsk commented
Actual PR https://github.com/VirtoCommerce/vc-module-payment/pull/29

2021-09-01 04:10 UTC, closed without merging